### ISSUE TITLE
missing alpha3

### ISSUE THREAD

**Issue by missinglink** [pelias/admin-lookup#22]
somehow this record is missing alpha3 information: http://pelias.mapzen.com/doc?id=osmway:176839394

```javascript
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "176839394",
        "layer": "osmway",
        "name": "Accelerator",
        "locality": "Singapore",
        "category": [
          
        ],
        "address": {
          
        },
        "text": "Accelerator, Singapore"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          103.82162,
          1.253774
        ]
      }
    }
  ],
  "bbox": [
    103.82162,
    1.253774,
    103.82162,
    1.253774
  ],
  "date": 1438168007658
}
```

**Comment by riordan** [comment]
@missinglink was this happening across builds?

**Comment by orangejulius** [comment]
I was curious about this one so I took a quick look. Accelerator is a [ride](https://www.youtube.com/watch?v=bSG2VHs7dK4) at Universal Studios Singapore. It's not on the main island of Singapore, but on a smaller island called Sentosa.

![screenshot from 2015-08-26 17 25 54](https://cloud.githubusercontent.com/assets/111716/9506737/c5622ce8-4c17-11e5-8be0-1f12dc559248.png)

Looking at the quattroshapes data, while there is an admin0 and locality covering the area of this island, it isn't covered by an admin1, admin2, or localadmin. Here's a Qgis capture with all those layers turned on. You can see that it only is covered by admin0 (blue)
![screenshot from 2015-08-26 17 26 02](https://cloud.githubusercontent.com/assets/111716/9506796/2e910f72-4c18-11e5-8db5-4b2f6d801e2d.png)

So based on that it looks like a flaw in the quattroshapes data, and thus will only be fixed by WOF.

**Comment by missinglink** [comment]
oh wow, I should have known, that's where the jsconf.asia afterparty was last year!
same again this year @serrynaimo?

**Comment by serrynaimo** [comment]
Not planned yet ;) But now thinking of complementary rollercoaster rides... Hmm
